### ISSUE TITLE
I get this when,I am creating stack using the provided template.yaml file 

### ISSUE THREAD

**Issue by LOGESH-R-06** [matwerber1/aws-alexa-smart-home-demo#10]
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 12. Resource with id [AlexaSkillFunction] is invalid. 'CodeUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter. Resource with id [AssociateThingToUserFunction] is invalid. 'CodeUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter. Resource with id [CloudFormationResponseLayer86b5683fdf] is invalid. 'ContentUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter. Resource with id [CognitoClientConfigurationProvider] is invalid. 'CodeUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter. Resource with id [CognitoClientSecretProvider] is invalid. 'CodeUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter. Resource with id [CognitoDomainProvider] is invalid. 'CodeUri' is not

**Comment by matwerber1** [comment]
How are you deploying the template? Are you trying to just load it into the AWS web console? If so, that won't work. 

You need to clone the repository and run the `./deploy.sh` script (after filling in appropriate values like your [Alexa Skill ID](https://github.com/matwerber1/aws-alexa-smart-home-demo/blob/cf96ce041b6275f944a7ab83ee03d3466d3966e0/deploy.sh#L6))

**Comment by LOGESH-R-06** [comment]
I also Implementing it for a esp8266 chip hardware which is already connected to the aws iot core thing.
Is it work with that because you are infracting skill with device shadow.

**Comment by matwerber1** [comment]
Without step-by-step instructions to reproduce your error, I'm unable to help. I'm going to close this issue... but if you want to provide more information, feel free to re-open.
