### ISSUE TITLE
Errors in CloudFormation - Stacks

### ISSUE THREAD

**Issue by zedb123** [matwerber1/aws-alexa-smart-home-demo#2]
Hi,

Sam Build seems to have a problem at UuidProvider (though tbh may not be the problem ! - just don't know - tried building in AWS CloudFormation by pressing Create Stack and putting in values manually - after pointing it in direction of template.yml file - didn't go down too well either)

Here's the message after putting in --verbose on sam build.

NODEJS installing in: G:\Dropbox\Projects\Alexa\aws-alexa-smart-home-demo-master\.aws-sam\build\UuidProvider
executing NPM: ['npm.cmd', 'install', '-q', '--no-audit', '--no-save', '--production']
NodejsNpmBuilder:NpmInstall failed
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\nodejs_npm\actions.py", line 108, in execute
    ["install", "-q", "--no-audit", "--no-save", "--production"], cwd=self.artifacts_dir
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\nodejs_npm\npm.py", line 85, in run
    raise NpmExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.nodejs_npm.npm.NpmExecutionError: NPM Failed: npm WARN cfprovider-uuid@1.0.0 No description
npm WARN cfprovider-uuid@1.0.0 No repository field.
npm WARN cfprovider-uuid@1.0.0 No license fie

Not too familiar with node.js - can't seem to load any of the previous files manually using npm either. Hope this is an easy fix !

Thanks

**Comment by zedb123** [comment]
Ran it this morning .. seems to work .. sorry

**Comment by matwerber1** [comment]
No problem! Sorry for super late reply. Glad to here you got it working. If the project was helpful or you have other thoughts, eager to hear them!!
