### ISSUE TITLE
deploy error 

### ISSUE THREAD

**Issue by kabcasa** [matwerber1/aws-alexa-smart-home-demo#3]
i don't understand i saw on previous issue that  this error was resolved but i still get it .

Error: Unable to upload artifact ../../lambda/layers/cfn-response referenced by                                                                      ContentUri parameter of CloudFormationResponseLayer resource.
Unable to locate credentials

        Deploying with following values
        ===============================
        Stack name                 : alexa-smart-home-demo
        Region                     : None
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {'AlexaSkillId': 'amzn1.ask.skill.27f4eb97-                                                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'AlexaVendorId': 'xxxxxxxxxxxx'}

Initiating deployment
=====================
Error: Failed to package template: /home/pi/alexa/aws-alexa-smart-home-demo-mast                                                                     er/.aws-sam/build/packaged.yaml.
 [Errno 2] No such file or directory: '/home/pi/alexa/aws-alexa-smart-home-demo-                                                                     master/.aws-sam/build/packaged.yaml'

________________________________________
i checked the /.aws-sam/build/VerifyCognitoTokenFunction/packege.json file 
{
  "name": "cfprovider-uuid",
  "version": "1.0.0",
  "dependencies": {
    "https": "^1.0.0",
    "node-jose": "^1.1.3"
  }
}

**Comment by kabcasa** [comment]
finally resolved after update credentials

**Comment by matwerber1** [comment]
Hi @kabcasa, I apologize for not responding sooner. Just so I understand, which credentials are you referring to? Was it your aws CLI credentials (e.g. `aws configure`), or was it something with the project that I can fix for future users? Again, sorry for late reply.

**Comment by kabcasa** [comment]
Hi @matwerber1 thank you for your message .
It was just to do with  update my token .
Nothing wrong on your project .
it's working perfectly.
