### ISSUE TITLE
Wont discover Devices at the end of Step 2

### ISSUE THREAD

**Issue by gannaramu** [matwerber1/aws-alexa-smart-home-demo#5]
Hello, 
Thank you for the detailed guide!. I was not able to see the device on the Alexa app even after Mapping our Skill's User ID (from Cognito) to  AWS IoT Thing. Any hints on where I am doing wrong?.

**Comment by gannaramu** [comment]
I think I was able to find the issue the User also need to update the Default enpoint on the alexa developer console with the alexa-smart-home-demo-AlexaSkillFunction-XXXXXXXXX lambda function's ARN

**Comment by matwerber1** [comment]
hey sorry for delay - glad you found it. I'm going to close this issue but please re-open if you encounter other issues.
