### ISSUE TITLE
Unable to receive SMS to mobile

### ISSUE THREAD

**Issue by raghuram-techno** [matwerber1/aws-alexa-smart-home-demo#7]
Hi matwerber1,

As Cognito was not sending any SMS to mobile for verification,

So i would like to change phone number to email verification , Can you please suggest where can we change ?

Thanks in advance

**Comment by matwerber1** [comment]
Hi, 

Closing due to insufficient information. 

Please provide more detailed explanation of your error, including error messages, screenshots, etc.
